Repository scientific-python/scientific-python-hugo-theme, pull requests merged in 2023-09, with the labels that each got.

#268 Add: Fallback font for symbols
  assets/theme-css/vars.css
  layouts/partials/css.html
Labels: bug

#274 Use ruff
  .pre-commit-config.yaml
Labels: type: Maintenance

#275 Update teams
  doc/static/teams/theme-team.html
Labels: type: Maintenance

#278 Use changelist
  .github/workflows/label-check.yaml
  .github/workflows/milestone-merged-prs.yaml
  requirements.txt
Labels: type: Maintenance

#277 Update prettier config
  .pre-commit-config.yaml
  assets/js/fresh.js
  assets/js/shortcuts.js
  assets/theme-css/fresh/core.scss
  assets/theme-css/fresh/partials/_animations.scss
  assets/theme-css/fresh/partials/_colors.scss
  assets/theme-css/fresh/partials/_navbar.scss
  assets/theme-css/fresh/partials/_utils.scss
Labels: type: Maintenance

#281 Use pre-commit bot
  .github/workflows/lint.yml
  .pre-commit-config.yaml
Labels: type: Maintenance

#282 Fix: (.navbar-logo-text) Color
  assets/theme-css/styles.css
Labels: type: Bug fix
