Repository scientific-python/scientific-python-hugo-theme, pull requests merged in 2023-12, with the labels that each got.

#418 Add copy button for code blocks
  assets/js/copy-code-blocks.js
  assets/theme-css/code.scss
  assets/theme-css/vars.css
Labels: type: Enhancement

#431 Updated keyfeatures.css
  assets/theme-css/keyfeatures.css
Labels: type: Enhancement

#434 Fix: (css.html) Unify types
  layouts/partials/css.html
Labels: type: Bug fix

#436 Meta: (Makefile) Add serve-dev rule
  Makefile
Labels: type: Maintenance

#435 Fix: (bulma.css) .navbar-dropdown background-color
  assets/theme-css/bulma.css
Labels: type: Bug fix

#437 Update font awesome
  layouts/partials/javascript.html
Labels: type: Maintenance

#439 Update mermaid
  layouts/partials/javascript.html
Labels: type: Maintenance

#440 Update hugo
  doc/netlify.toml
Labels: type: Maintenance

#441 Update dart sass
  doc/netlify.toml
Labels: type: Maintenance

#442 Update PST style
  assets/theme-css/pst/abstracts/_color.scss
  assets/theme-css/pst/content/_admonitions.scss
  assets/theme-css/pst/content/_quotes.scss
Labels: type: Maintenance

#443 Apply purgecss
  assets/theme-css/footer.css
  assets/theme-css/posts.css
  assets/theme-css/styles.css
Labels: type: Maintenance

#444 Refactor bulma navbar css
  assets/theme-css/bulma.css
  layouts/partials/navbar.html
Labels: type: Maintenance
