Repository scientific-python/scientific-python-hugo-theme, pull requests merged in 2023-10, with the labels that each got.

#276 Fix hero title and icon alignment on narrower screens
  assets/theme-css/styles.css
Labels: type: Bug fix

#283 Change: (posts.css) Condense and simplify
  assets/theme-css/posts.css
Labels: type: Enhancement

#287 Fix: (light-mode.css) Specify --colorBlockBackground
  assets/theme-css/light-mode.css
Labels: type: Bug fix

#284 Blog dark theme issues
  assets/theme-css/content.css
  assets/theme-css/panel.css
Labels: type: Enhancement

#289 Improvements to blog.scientific-python.org
  assets/theme-css/panel.css
  layouts/partials/single/content.html
Labels: type: Enhancement

#292 Fixes related to scientific-python.org/grants (#291)
  assets/icons/calendar.svg
  assets/icons/person.svg
  assets/theme-css/posts.css
  assets/theme-css/styles.css
Labels: type: Enhancement

#293 Meta: (Makefile) Serve with --poll, etc.
  Makefile
Labels: type: Maintenance

#294 Revert "Fixes related to scientific-python.org/grants (#291) (#292)"
  assets/icons/calendar.svg
  assets/icons/person.svg
  assets/theme-css/posts.css
  assets/theme-css/styles.css
Labels: type: Bug fix

#297 Add netlify target
  Makefile
Labels: type: Maintenance

#298 Build multiple sites
  Makefile
Labels: type: Enhancement

#300 Test on main site
  Makefile
Labels: type: Maintenance

#303 Use dart sass
  Makefile
  doc/netlify.toml
  layouts/partials/css.html
Labels: type: Enhancement

#301 Use pydata-sphinx-theme admonition styling
  assets/theme-css/pst/abstracts/_accessibility.scss
  assets/theme-css/pst/abstracts/_all.scss
  assets/theme-css/pst/abstracts/_color.scss
  assets/theme-css/pst/abstracts/_links.scss
  assets/theme-css/pst/abstracts/_mixins.scss
  assets/theme-css/pst/content/_admonitions.scss
  assets/theme-css/pst/pydata-sphinx-theme.scss
  assets/theme-css/pst/variables/_admonitions.scss
  assets/theme-css/pst/variables/_color.scss
  assets/theme-css/pst/variables/_fonts.scss
  assets/theme-css/pst/variables/_icons.scss
  assets/theme-css/pst/variables/_layout.scss
  layouts/partials/css.html
  layouts/shortcodes/admonition.html
Labels: type: Enhancement

#306 Only build site previews for PRs
  Makefile
  README.md
  doc/netlify.toml
Labels: type: Maintenance

#309 Run linter
  README.md
  assets/theme-css/posts.css
  assets/theme-css/pst/abstracts/_mixins.scss
Labels: type: Maintenance

#310 Enable font-awesome
  layouts/partials/javascript.html
Labels: type: Enhancement

#308 Add javascript dark toggle mode
  assets/js/dark.js
Labels: type: Enhancement

#311 Revert change that only provided partial context
  layouts/partials/single/content.html
Labels: type: Bug fix

#312 Add missing admonitions
  layouts/shortcodes/admonition.html
Labels: type: Enhancement

#315 Update getstarted button
  doc/config.yaml
Labels: type: Documentation

#313 Use pst page-toc
  assets/theme-css/dark-mode.css
  assets/theme-css/shortcuts.css
  layouts/partials/section/section.html
  layouts/partials/single/content.html
  static/images/icons/list-bulleted.svg
Labels: type: Enhancement

#317 Purge unused bulma CSS
  assets/theme-css/bulma.css
  assets/theme-css/navbar-burger.css
  layouts/partials/css.html
Labels: type: Maintenance

#318 Add back missing pieces of bulma
  assets/theme-css/bulma.css
  assets/theme-css/navbar-burger.css
Labels: type: Maintenance

#322 Add mission and values admonitions
  layouts/shortcodes/admonition.html
Labels: type: Enhancement

#324 Do not render duplicate shortcodes
  Makefile
  doc/netlify.toml
Labels: type: Maintenance

#319 Use purgeCSS to reduce fresh CSS
  assets/theme-css/fresh.css
  assets/theme-css/fresh/core.scss
  assets/theme-css/fresh/partials/_animations.scss
  assets/theme-css/fresh/partials/_colors.scss
  assets/theme-css/fresh/partials/_navbar.scss
  assets/theme-css/fresh/partials/_utils.scss
  layouts/partials/css.html
Labels: type: Maintenance

#325 Add date generated as comment
  layouts/_default/baseof.html
Labels: type: Enhancement

#323 Disable taxonomy index page
  config.yaml
Labels: type: Maintenance

#326 Remove unused notices
  assets/theme-css/light-mode.css
  assets/theme-css/notices.css
  assets/theme-css/vars.css
  layouts/shortcodes/notice.html
Labels: type: Maintenance

#330 Remove unused fadeFrontPage
  assets/js/fresh.js
  assets/theme-css/fresh.css
  config.yaml
  layouts/_default/baseof.html
Labels: type: Maintenance

#331 Remove jquery usage in theme JS
  assets/js/fresh.js
  assets/js/shortcuts.js
  assets/theme-css/shortcuts.css
  layouts/partials/javascript.html
  layouts/partials/section/section.html
  layouts/partials/single/content.html
Labels: type: Maintenance

#333 Only handle shortcuts if they are present on the page
  assets/js/shortcuts.js
Labels: type: Maintenance

#335 Update hugo
  doc/netlify.toml
Labels: type: Maintenance

#337 Use preconnects to speed up font loading
  doc/netlify.toml
  layouts/partials/css.html
Labels: type: Enhancement

#329 Prepare for better PST alignment
  assets/js/shortcuts.js
  assets/theme-css/bulma.css
  assets/theme-css/code-highlight.css
  assets/theme-css/content.css
  assets/theme-css/dark-mode.css
  assets/theme-css/keyfeatures.css
  assets/theme-css/light-mode.css
  assets/theme-css/panel.css
  assets/theme-css/posts.css
  assets/theme-css/pst/base/_base.scss
  assets/theme-css/pst/components/_breadcrumbs.scss
  assets/theme-css/pst/content/_code.scss
  assets/theme-css/pst/content/_toctree.scss
  assets/theme-css/pst/pydata-sphinx-theme.scss
  assets/theme-css/shortcuts.css
  assets/theme-css/styles.css
  doc/config.yaml
  doc/content/examples/_index.md
  doc/content/examples/kitchen-sink/_index.md
  doc/content/examples/kitchen-sink/admonitions.md
  doc/content/examples/kitchen-sink/typography.md
  doc/content/features.md
  layouts/_default/_markup/render-codeblock.html
  layouts/_default/_markup/render-heading.html
  layouts/partials/breadcrumbs.html
  layouts/partials/section/section.html
  layouts/partials/single/content.html
  layouts/shortcodes/toctree.html
Labels: type: Enhancement

#338 Render mermaid via code blocks, instead of shortcodes
  doc/content/features.md
  layouts/_default/_markup/render-codeblock-mermaid.html
  layouts/partials/javascript.html
  layouts/shortcodes/mermaid.html
Labels: type: Enhancement

#342 Document release process
  RELEASE.md
Labels: type: Documentation

#343 Ignore bot contributions
  RELEASE.md
  pyproject.toml
Labels: type: Maintenance

#344 Use box-shadow feature boxes
  assets/theme-css/keyfeatures.css
  assets/theme-css/styles.css
Labels: type: Enhancement

#346 Move section shortcuts to LHS
  layouts/partials/section/section.html
Labels: type: Bug fix

#347 Remove bulma subheading styling
  assets/theme-css/bulma.css
  assets/theme-css/styles.css
Labels: type: Maintenance
