Repository scientific-python/scientific-python-hugo-theme, pull requests merged in 2023-11, with the labels that each got.

#351 Update mermaid (10.6.0)
  layouts/partials/javascript.html
Labels: type: Maintenance

#352 Update font-awesome
  layouts/partials/javascript.html
Labels: type: Maintenance

#350 Cleanup CSS
  assets/theme-css/bulma.css
  assets/theme-css/content.css
  assets/theme-css/keyfeatures.css
  assets/theme-css/panel.css
  assets/theme-css/styles.css
Labels: type: Maintenance

#356 Team gallery: use less general CSS class names
  assets/theme-css/teams.css
  tools/team_query.py
Labels: type: Bug fix

#357 Improve blog post metadata rendering
  assets/theme-css/posts.css
  doc/config.yaml
  layouts/partials/posts/meta.html
Labels: type: Enhancement

#360 Use pst-color-text-muted (not colorSecondaryDark)
  assets/theme-css/dark-mode.css
  assets/theme-css/light-mode.css
  assets/theme-css/posts.css
  assets/theme-css/styles.css
Labels: type: Enhancement

#358 Remove navbar clone; instead render navbar using `position: sticky`
  assets/js/shortcuts.js
  assets/theme-css/fresh.css
  layouts/_default/baseof.html
Labels: type: Enhancement

#359 Reduce flashing on page load
  assets/js/00_dark.js
  assets/theme-css/dark-mode.css
  layouts/_default/baseof.html
Labels: type: Enhancement

#364 Add back tag cloud removed by accident
  layouts/partials/posts/list.html
Labels: type: Maintenance

#363 Add back featuredImage that was removed by accident
  layouts/partials/posts/post.html
Labels: type: Maintenance

#367 Add blog CSS
  assets/theme-css/posts.css
Labels: type: Enhancement

#370 Add details shortcode
  layouts/shortcodes/details.html
Labels: type: Enhancement

#369 Stick footer to bottom
  assets/theme-css/styles.css
  assets/theme-css/vars.css
Labels: type: Enhancement

#371 Cleanup colors
  assets/theme-css/code-highlight.css
  assets/theme-css/dark-mode.css
  assets/theme-css/light-mode.css
  assets/theme-css/news.css
  assets/theme-css/styles.css
Labels: type: Maintenance

#373 Make button respond to hover and delete cruft
  assets/theme-css/styles.css
  layouts/partials/hero-body.html
  layouts/partials/hero.html
Labels: type: Enhancement

#372 Update theme gallery classes
  doc/static/teams/theme-team.html
Labels: type: Maintenance

#366 Use mathjax
  layouts/partials/head.html
Labels: type: Enhancement

#375 Avoid narrow shrinking of posts on wide screens
  assets/theme-css/posts.css
Labels: type: Bug fix

#376 Do label check after first review
  .github/workflows/label-check.yaml
Labels: type: Maintenance

#377 Fix Scientific Python font in header; also illustrates using custom CSS
  doc/assets/css/custom.css
Labels: type: Documentation

#379 Remove unused styles
  assets/js/fresh.js
  assets/theme-css/bulma.css
Labels: type: Maintenance

#380 Add tabs/tab shortcodes
  assets/js/tabs.js
  assets/theme-css/bulma.css
  assets/theme-css/tabs.css
  layouts/partials/hero.html
  layouts/shortcodes/tab.html
  layouts/shortcodes/tabs.html
Labels: type: Enhancement

#383 Use PST lists styling
  assets/theme-css/bulma.css
  assets/theme-css/content.css
  assets/theme-css/pst/content/_lists.scss
  assets/theme-css/pst/pydata-sphinx-theme.scss
Labels: type: Enhancement

#384 Remove unused bulman is-light
  assets/theme-css/bulma.css
Labels: type: Maintenance

#381 Simplify panel styling
  assets/theme-css/panel.css
  layouts/partials/panel.html
Labels: type: Enhancement

#386 Fix tabs' borders
  assets/theme-css/tabs.css
  layouts/shortcodes/tabs.html
Labels: type: Bug fix

#389 Change: (Makefile) Clone site repos shallowly
  Makefile
Labels: type: Maintenance

#391 Add: "More" links after post summaries
  assets/theme-css/posts.css
  layouts/partials/posts/summary.html
Labels: type: Enhancement

#387 Tabs tidy and shortcuts
  assets/js/shortcuts.js
  assets/theme-css/tabs.css
  layouts/partials/panel.html
  layouts/shortcodes/tabs.html
Labels: type: Enhancement

#394 Fix footer column link's styling
  assets/theme-css/styles.css
Labels: type: Bug fix

#396 Wrap tabs when screen shrinks
  assets/theme-css/tabs.css
Labels: type: Enhancement

#400 Do not escape heading anchors unnecessarily
  layouts/_default/_markup/render-heading.html
Labels: type: Bug fix

#401 Docs: (getstarted.md) Update instructions
  doc/content/getstarted.md
Labels: type: Documentation

#399 Reformat footer without unordered lists
  assets/theme-css/footer.css
  assets/theme-css/styles.css
  layouts/partials/footer.html
Labels: type: Enhancement

#403 Docs: Add tabs shortcode example
  assets/theme-css/styles.css
  layouts/shortcodes/tabs.html
  tools/render_shortcode_docs.py
Labels: type: Bug fix, type: Enhancement

#404 Remove unused keyframes and fadeIn*
  assets/theme-css/bulma.css
  assets/theme-css/fresh.css
Labels: type: Maintenance

#407 Fix: (styles.css) .navbar-menu colors
  assets/theme-css/styles.css
Labels: type: Bug fix

#406 Docs: Add toctree shortcode docs and render option in the Python script
  layouts/shortcodes/toctree.html
  tools/render_shortcode_docs.py
Labels: type: Documentation, type: Enhancement

#408 Remove unused navbar-clone.html
  layouts/partials/navbar-clone.html
Labels: type: Maintenance

#405 Remove unused bulma table, tags, and progress
  assets/theme-css/bulma.css
  assets/theme-css/styles.css
  assets/theme-css/tables.css
Labels: type: Maintenance

#409 Remove unused team shortcodes
  doc/content/features.md
  layouts/shortcodes/team.html
  layouts/shortcodes/team_member.html
Labels: type: Maintenance

#395 Cleanup old bulma css
  assets/theme-css/bulma.css
  assets/theme-css/styles.css
Labels: type: Maintenance

#410 Remove unneeded section styling
  assets/theme-css/bulma.css
  assets/theme-css/fresh.css
Labels: type: Maintenance

#411 Remove bulma box-sizing
  assets/theme-css/bulma.css
Labels: type: Maintenance

#412 Use correct color for tabs border
  assets/theme-css/tabs.css
Labels: type: Bug fix

#415 Use PST blockquote styling
  assets/theme-css/pst/content/_quotes.scss
  assets/theme-css/pst/pydata-sphinx-theme.scss
  assets/theme-css/styles.css
  doc/content/examples/kitchen-sink/blocks.md
Labels: type: Enhancement

#417 Use border-box sizing
  assets/theme-css/styles.css
Labels: type: Bug fix

#402 Fix: (posts, shortcuts) Adjust width, padding for narrower screens
  assets/theme-css/content.css
  assets/theme-css/posts.css
  assets/theme-css/shortcuts.css
  layouts/_default/section.html
  layouts/_default/single.html
  layouts/partials/posts/list.html
  layouts/partials/posts/post.html
  layouts/partials/section/section.html
Labels: type: Bug fix

#421 Navbar clone cleanup
  assets/theme-css/fresh.css
Labels: type: Maintenance

#422 Remove style for unused bulma classes
  assets/theme-css/bulma.css
Labels: type: Maintenance

#423 Fix color for footer links on hover
  assets/theme-css/footer.css
Labels: type: Bug fix

#424 Avoid duplicate css extension
  layouts/partials/css.html
Labels: type: Maintenance

#420 Allow disabling dark mode in configuration
  .prettierignore
  assets/js/00_dark.js
  assets/theme-css/dark-mode.css
  config.yaml
  layouts/_default/baseof.html
  layouts/partials/javascript.html
Labels: type: Maintenance

#425 Fix bulma burger issues
  assets/theme-css/bulma.css
  assets/theme-css/styles.css
Labels: type: Bug fix

#427 Use old style label-check action
  .github/workflows/label-check.yaml
Labels: type: Maintenance

#426 Unify dropdown menu hover color with other links
  assets/theme-css/fresh.css
  assets/theme-css/styles.css
Labels: type: Bug fix

#428 Consolidate navbar CSS
  assets/theme-css/fresh.css
  assets/theme-css/navbar.css
  assets/theme-css/styles.css
Labels: type: Maintenance

#413 Allow sites to use local Sass files
  assets/theme-css/fresh.css
  doc/content/getstarted.md
  layouts/partials/css.html
Labels: type: Enhancement

#429 Change/Fix: Include "theme-css/*.scss" files
  layouts/partials/css.html
Labels: type: Bug fix

#430 Update hugo
  doc/netlify.toml
Labels: type: Maintenance
