Repository scientific-python/scientific-python-hugo-theme, pull requests merged in 2024-02, with the labels that each got.

#464 Add a placeholder for blog comments
  layouts/partials/posts/comments.html
  layouts/partials/posts/post.html
Labels: type: Enhancement

#465 Mention comments partial feature
  doc/content/features.md
Labels: type: Documentation

#467 Update hugo and dart-sass
  doc/netlify.toml
Labels: type: Maintenance

#463 Add PST cards
  assets/theme-css/pst-deps/sphinx-design/_card.scss
  assets/theme-css/scientific-python-hugo-theme.scss
  doc/config.yaml
  layouts/shortcodes/card.html
Labels: type: Enhancement

#466 Add PST cards in grid
  assets/theme-css/pst-deps/sphinx-design/_grid.scss
  assets/theme-css/scientific-python-hugo-theme.scss
  layouts/shortcodes/grid.html
Labels: type: Enhancement

#468 Use toml for card data
  layouts/shortcodes/badge.html
  layouts/shortcodes/card.html
  layouts/shortcodes/grid.html
Labels: type: Enhancement

#470 Update PST scss
  assets/theme-css/pst/components/_breadcrumbs.scss
  assets/theme-css/pst/variables/_color.scss
Labels: type: Maintenance

#469 Implement clickable cards
  assets/theme-css/content.css
  assets/theme-css/pst-deps/sphinx-design/_card.scss
  layouts/shortcodes/card.html
Labels: type: Enhancement

#471 Add PST dropdowns
  assets/theme-css/pst-deps/sphinx-design/_dropdown.scss
  assets/theme-css/pst-deps/sphinx-design/_icons.scss
  assets/theme-css/pst/extensions/_togglebutton.scss
  assets/theme-css/pst/pydata-sphinx-theme.scss
  assets/theme-css/scientific-python-hugo-theme.scss
  layouts/shortcodes/dropdown.html
Labels: type: Enhancement

#473 Add dropdown in card
  layouts/shortcodes/card.html
  layouts/shortcodes/dropdown.html
Labels: type: Enhancement

#472 Fixing grid shortcode
  layouts/shortcodes/grid.html
Labels: type: Enhancement

#475 Fix grid layout
  assets/theme-css/pst-deps/sphinx-design/_badges.scss
  assets/theme-css/pst-deps/sphinx-design/_card.scss
  assets/theme-css/pst-deps/sphinx-design/_grid.scss
  assets/theme-css/pst-deps/sphinx-design/_icons.scss
  assets/theme-css/scientific-python-hugo-theme.scss
  assets/theme-css/sphinx-design/_badge.scss
  assets/theme-css/sphinx-design/_borders.scss
  assets/theme-css/sphinx-design/_button.scss
  assets/theme-css/sphinx-design/_cards.scss
  assets/theme-css/sphinx-design/_colors.scss
  assets/theme-css/sphinx-design/_display.scss
  assets/theme-css/sphinx-design/_dropdown.scss
  assets/theme-css/sphinx-design/_grids.scss
  assets/theme-css/sphinx-design/_sizing.scss
  assets/theme-css/sphinx-design/_spacing.scss
  assets/theme-css/sphinx-design/_text.scss
  assets/theme-css/sphinx-design/_variables.scss
  assets/theme-css/sphinx-design/index.scss
  layouts/shortcodes/card.html
  layouts/shortcodes/grid.html
Labels: type: Enhancement

#478 Keep scss separate
  assets/theme-css/scientific-python-hugo-theme.scss
  assets/theme-css/spht/index.scss
  layouts/partials/css.html
Labels: type: Maintenance

#483 Add button shortcode
  layouts/shortcodes/button.html
Labels: type: Enhancement

#479 Move keyfeatures out of config
  doc/config.yaml
  doc/content/_index.md
  layouts/index.html
Labels: type: Enhancement

#485 Focus social media
  assets/icons/mastodon.svg
  doc/config.yaml
Labels: type: Maintenance

#486 Update pre-commit repos
  .pre-commit-config.yaml
Labels: type: Maintenance

#487 Make hero optional
  config.yaml
Labels: type: Enhancement

#488 Add blog frontpage shortcode
  layouts/shortcodes/blog.html
Labels: type: Enhancement

#490 Add grid columns option
  layouts/shortcodes/grid.html
Labels: type: Enhancement

#491 Update web components
  doc/content/user_guide/web-components.md
Labels: type: Documentation

#492 Use columns on homepage grid
  doc/content/_index.md
Labels: type: Maintenance

#493 Fix fosstodon link
  doc/config.yaml
Labels: type: Documentation

#495 Fix blog build
  Makefile
  doc/config.yaml
Labels: type: Maintenance

#494 Update hugo
  doc/content/getstarted.md
  doc/netlify.toml
  layouts/shortcodes/toctree.html
Labels: type: Maintenance

#497 Add atom xml feed as subtheme
  config.yaml
Labels: type: Bug fix

#498 Remove panel
  assets/theme-css/panel.css
  layouts/index.html
  layouts/partials/panel.html
  layouts/shortcodes/blog.html
Labels: type: Maintenance

#499 Remove keyfeatures
  assets/theme-css/keyfeatures.css
  layouts/index.html
  layouts/partials/keyfeatures.html
Labels: type: Maintenance

#500 Update hugo
  doc/netlify.toml
Labels: type: Maintenance

#501 Update mermaid
  layouts/partials/javascript.html
Labels: type: Maintenance

#503 Add author profiles
  layouts/partials/posts/meta.html
Labels: type: Enhancement

#505 Add image shortcode
  assets/theme-css/bulma.css
  assets/theme-css/styles.css
  layouts/shortcodes/image.html
Labels: type: Enhancement

#506 Add include shortcode
  layouts/shortcodes/include.html
Labels: type: Enhancement

#509 Use toml for grids
  layouts/shortcodes/grid1.html
Labels: type: Enhancement

#508 Document figures
  assets/theme-css/styles.css
  doc/content/features.md
  layouts/shortcodes/grid1.html
Labels: type: Documentation

#511 Add file option to grid shortcode
  assets/theme-css/bulma.css
  assets/theme-css/styles.css
  layouts/shortcodes/grid1.html
Labels: type: Enhancement

#512 Support grid items and cards
  layouts/shortcodes/grid1.html
Labels: type: Enhancement

#513 Add grid outline option
  layouts/shortcodes/grid1.html
Labels: type: Enhancement

#510 Use grid of cards for team gallery
  Makefile
  doc/content/about/_index.md
  doc/content/about/theme-team.toml
  doc/static/teams/theme-team.html
  tools/team_query.py
Labels: type: Enhancement

#514 Move icon styling out of bulma
  assets/theme-css/bulma.css
  assets/theme-css/styles.css
Labels: type: Maintenance

#516 Update requirements
  requirements.txt
Labels: type: Maintenance

#515 Add field list shortcode and partial
  assets/theme-css/lists.css
  layouts/partials/_elements/field-list.html
  layouts/shortcodes/field-list.html
Labels: type: Enhancement

#517 Hide deprecated shortcodes
  layouts/shortcodes/card.html
  layouts/shortcodes/grid.html
  layouts/shortcodes/youtube.html
Labels: type: Maintenance

#518 Update hugo
  doc/netlify.toml
Labels: type: Maintenance

#519 Add back image-default
  assets/theme-css/styles.css
Labels: type: Maintenance

#520 Update image and grid shortcodes
  assets/theme-css/styles.css
  doc/content/about/theme-team.toml
  layouts/shortcodes/grid1.html
  layouts/shortcodes/image.html
  tools/team_query.py
Labels: type: Enhancement
