Repository scientific-python/scientific-python-hugo-theme, pull requests merged in 2024-09, with the labels that each got.

#639 Style mermaid tooltips
  assets/theme-css/styles.css
Labels: type: Bug fix

#615 #607: Pagefind Search
  .gitignore
  Makefile
  assets/js/search.js
  assets/theme-css/search.css
  config.yaml
  doc/Makefile
  doc/config.yaml
  layouts/_default/baseof.html
  layouts/partials/css.html
  layouts/partials/javascript.html
  layouts/partials/navbar.html
  layouts/partials/search.html
Labels: type: Enhancement

#640 Update hugo (0.134.3)
  doc/netlify.toml
Labels: type: Maintenance

#637 Correctly convert spaces in tags to dashes
  layouts/partials/posts/meta.html
Labels: type: Enhancement
