Repository scientific-python/scientific-python-hugo-theme, pull requests merged in 2024-03, with the labels that each got.

#521 Separate hero css
  assets/theme-css/hero.css
  assets/theme-css/styles.css
Labels: type: Maintenance

#523 Separate backtotop css
  assets/theme-css/backtotop.css
  assets/theme-css/fresh.css
  assets/theme-css/styles.css
Labels: type: Maintenance

#525 Remove level css
  assets/theme-css/bulma.css
  assets/theme-css/footer.css
  layouts/partials/footer.html
Labels: type: Maintenance

#526 Add sidebar
  assets/theme-css/bulma.css
  assets/theme-css/styles.css
  layouts/shortcodes/sidebar.html
Labels: type: Enhancement

#524 Use PST colors for backtotop
  assets/theme-css/backtotop.css
Labels: type: Enhancement

#527 Update hugo
  doc/netlify.toml
Labels: type: Maintenance

#528 Update release process notes
  RELEASE.md
Labels: type: Maintenance

#529 Refactor cards and items into partials
  layouts/partials/_elements/card.html
  layouts/partials/_elements/item.html
  layouts/shortcodes/grid1.html
Labels: type: Maintenance

#530 Refactor grid into partial
  layouts/partials/_elements/grid.html
  layouts/shortcodes/grid1.html
Labels: type: Enhancement

#531 Add optional levels parameter to toctree
  layouts/shortcodes/toctree.html
Labels: type: Enhancement

#533 Update team galleries
  doc/content/about/theme-team.toml
  tools/team_query.py
Labels: type: Enhancement

#535 Remove fresh cruft
  assets/theme-css/fresh.css
  static/images/loaders/rings.svg
Labels: type: Maintenance

#534 Update hugo
  doc/netlify.toml
Labels: type: Maintenance

#536 Update dart sass
  doc/netlify.toml
Labels: type: Maintenance

#537 Use column value for smallest screens
  layouts/partials/_elements/grid.html
Labels: type: Bug fix

#539 Use admonition partial
  layouts/partials/_elements/admonition.html
  layouts/shortcodes/admonition.html
Labels: type: Enhancement

#540 Use image partial
  layouts/partials/_elements/image.html
  layouts/shortcodes/image.html
Labels: type: Enhancement

#541 BUG: fixed `showOnTop`
  layouts/partials/posts/post.html
Labels: type: Bug fix

#542 Fix processing of scss
  layouts/partials/css.html
Labels: type: Bug fix

#543 Replace grid with grid1 shortcode
  layouts/shortcodes/grid.html
  layouts/shortcodes/grid1.html
Labels: type: Maintenance

#545 Use new grid syntax
  doc/content/_index.md
Labels: type: Maintenance

#544 Remove old team gallery styling
  assets/theme-css/teams.css
Labels: type: Maintenance

#546 Add figure shortcode with PST styling
  Makefile
  assets/theme-css/pst/content/_figures.scss
  assets/theme-css/pst/pydata-sphinx-theme.scss
  assets/theme-css/styles.css
  doc/content/features.md
  layouts/partials/_elements/image.html
  layouts/shortcodes/figure.html
Labels: type: Enhancement

#547 Add loading attribute to image partial
  layouts/partials/_elements/image.html
  layouts/shortcodes/image.html
Labels: type: Enhancement

#550 Add figure functionality for numpy.org
  assets/theme-css/styles.css
  layouts/shortcodes/figure.html
Labels: type: Enhancement

#551 Update pre-commit repos
  .pre-commit-config.yaml
Labels: type: Maintenance

#553 Remove bulma box styling
  assets/theme-css/bulma.css
Labels: type: Maintenance

#552 Remove grid1 shortcode
  doc/content/about/_index.md
  layouts/shortcodes/grid.html
  layouts/shortcodes/grid1.html
Labels: type: Maintenance

#554 Center image in figures
  layouts/shortcodes/figure.html
Labels: type: Enhancement

#555 Remove bulma columns class
  assets/theme-css/bulma.css
  layouts/partials/footer.html
Labels: type: Maintenance

#556 Remove unused bulma css
  assets/theme-css/bulma.css
Labels: type: Maintenance

#557 Remove bulma title css
  assets/theme-css/bulma.css
Labels: type: Maintenance

#558 Remove unneeded bulma css
  assets/theme-css/bulma.css
  assets/theme-css/videos.css
Labels: type: Maintenance

#560 Remove unused class styling
  layouts/partials/section/section.html
Labels: type: Maintenance

#562 Remove reference to unsused class is-max-desktop
  assets/theme-css/bulma.css
Labels: type: Maintenance

#563 Remove is-max-widescreen class
  assets/theme-css/bulma.css
  layouts/partials/footer.html
  layouts/partials/navbar.html
Labels: type: Maintenance

#564 Update navbar styling
  assets/theme-css/navbar.css
  doc/config.yaml
  layouts/partials/navbar.html
Labels: type: Enhancement

#565 Refactor navbar css
  assets/theme-css/navbar.css
  layouts/partials/navbar.html
  layouts/partials/translation.html
Labels: type: Enhancement

#567 Unify navbar link styling (following PST)
  assets/theme-css/navbar.css
Labels: type: Enhancement

#561 Use rem for fonts, margins, and padding
  assets/theme-css/backtotop.css
  assets/theme-css/content.css
  assets/theme-css/footer.css
  assets/theme-css/lists.css
  assets/theme-css/news.css
  assets/theme-css/posts.css
  assets/theme-css/shortcuts.css
  assets/theme-css/styles.css
  assets/theme-css/tabs.css
  assets/theme-css/videos.css
Labels: type: Maintenance

#569 Add links to preview sites for PRs
  Makefile
  README.md
  tools/add_preview_links.py
Labels: type: Maintenance

#570 Remove yamlToTable documentation
  layouts/shortcodes/figure.html
  layouts/shortcodes/yamlToTable.html
Labels: type: Documentation

#571 Add tables to examples with PST styling
  assets/theme-css/pst/content/_tables.scss
  assets/theme-css/pst/pydata-sphinx-theme.scss
  doc/content/examples/kitchen-sink/tables.md
  layouts/shortcodes/yamlToTable.html
Labels: type: Enhancement

#574 Add link to scientific-python.org preview
  Makefile
  tools/add_preview_links.py
Labels: type: Maintenance

#576 Add link to learn preview
  Makefile
  tools/add_preview_links.py
Labels: type: Maintenance
