Repository scientific-python/scientific-python-hugo-theme, pull requests merged in 2024-01, with the labels that each got.

#448 Skip autoupdating prettier-mirror
  .pre-commit-config.yaml
Labels: type: Maintenance

#449 Temporarily schedule pre-cmmmit-ci auotupdate weekly
  .pre-commit-config.yaml
Labels: type: Maintenance

#451 Autoupdate pre-commit quarterly
  .pre-commit-config.yaml
Labels: type: Maintenance

#452 Run pre-commit autoupdate
  .pre-commit-config.yaml
Labels: type: Maintenance

#446 Add PDST badges
  assets/theme-css/pst/components/_badges.scss
  assets/theme-css/pst/extensions/_sphinx_design.scss
  assets/theme-css/pst/pydata-sphinx-theme.scss
  doc/content/user_guide/web-components.md
  layouts/shortcodes/badge.html
Labels: type: Enhancement

#455 Add missing f in f-string
  tools/team_query.py
Labels: type: Maintenance

#454 Simplify navbar
  assets/theme-css/bulma.css
  assets/theme-css/navbar.css
  assets/theme-css/styles.css
  layouts/partials/navbar.html
Labels: type: Maintenance

#456 Consolidate navbar styling
  assets/theme-css/bulma.css
  assets/theme-css/navbar.css
Labels: type: Maintenance

#453 Group scss components
  assets/theme-css/pst-deps/sphinx-design/_badges.scss
  assets/theme-css/pst/pydata-sphinx-theme.scss
  assets/theme-css/scientific-python-hugo-theme.scss
  assets/theme-css/spht/_code.scss
  layouts/partials/css.html
Labels: type: Maintenance

#459 Increase color contrast in footer
  assets/theme-css/footer.css
Labels: type: Enhancement

#462 Use default font size for cta button
  assets/theme-css/styles.css
Labels: type: Enhancement

#461 Fix navbar / active burger issue (#460)
  assets/theme-css/navbar.css
Labels: type: Bug fix
