Repository scientific-python/scientific-python-hugo-theme, pull requests merged in 2024-05, with the labels that each got.

#595 Organize into User Guide
  doc/config.yaml
  doc/content/user_guide/_index.md
  doc/content/user_guide/features.md
  doc/content/user_guide/getstarted.md
  doc/content/user_guide/web-components.md
Labels: type: Documentation

#594 Improve color handling
  assets/theme-css/footer.css
  assets/theme-css/hero.css
  assets/theme-css/news.css
  assets/theme-css/vars.css
  doc/content/user_guide/_index.md
  doc/content/user_guide/features.md
  doc/content/user_guide/styling.md
Labels: type: Maintenance

#597 Refactor font loading
  assets/theme-css/hero.css
  assets/theme-css/vars.css
  config.yaml
  doc/assets/css/custom.css
  doc/config.yaml
  doc/content/user_guide/styling.md
  layouts/_default/baseof.html
  layouts/partials/css.html
  layouts/partials/head.html
  layouts/partials/mathjax.html
Labels: type: Enhancement

#603 Implement columns for grid items
  layouts/partials/_elements/card.html
  layouts/partials/_elements/item.html
  layouts/shortcodes/grid.html
Labels: type: Enhancement

#604 Fix grid item
  layouts/partials/_elements/item.html
Labels: type: Bug fix

#605 Fix breadcrumbs
  layouts/partials/breadcrumbs.html
Labels: type: Bug fix

#608 Update hugo
  doc/netlify.toml
Labels: type: Maintenance

#609 Update dart sass
  doc/netlify.toml
Labels: type: Maintenance

#613 Document how to add custom html header content
  doc/content/user_guide/features.md
  layouts/_default/baseof.html
  layouts/partials/head.html
Labels: type: Documentation
