Repository scientific-python/scientific-python-hugo-theme, pull requests merged in 2025-01, with the labels that each got.

#655 style: align `backtotop` icon along main axis
  assets/theme-css/backtotop.css
Labels: type: Enhancement

#659 Update hugo
  doc/netlify.toml
Labels: type: Maintenance

#660 Update dart sass
  doc/netlify.toml
Labels: type: Maintenance

#661 Update scss from pst
  assets/theme-css/pst/abstracts/_links.scss
  assets/theme-css/pst/abstracts/_mixins.scss
  assets/theme-css/pst/base/_base.scss
  assets/theme-css/pst/content/_code.scss
  assets/theme-css/pst/extensions/_sphinx_design.scss
  assets/theme-css/pst/extensions/_togglebutton.scss
  assets/theme-css/pst/variables/_bootstrap.scss
  assets/theme-css/pst/variables/_color.scss
Labels: type: Enhancement

#662 Remove custom youtube shortcode
  assets/theme-css/videos.css
  doc/content/video-page.md
  layouts/partials/javascript.html
  layouts/shortcodes/youtube.html
Labels: type: Maintenance

#663 Add zizmor pre-commit
  .github/workflows/milestone-merged-prs.yaml
  .pre-commit-config.yaml
Labels: type: Maintenance

#665 Update readme
  README.md
Labels: type: Documentation
